version: '3.7'
services:
 dynamodb-local:
   image: amazon/dynamodb-local:latest
   restart: always
   container_name: dynamodb-local
   ports:
    - "8000:8000"
   command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

   aws dynamodb create-table \
    --table-name test-dev \
    --attribute-definitions \
        AttributeName=userId,AttributeType=S \
    --key-schema \
        AttributeName=userId,KeyType=HASH \
--provisioned-throughput \
        ReadCapacityUnits=10,WriteCapacityUnits=5